{% set name = "websocket-server" %}
{% set version = "0.6.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/websocket_server-{{ version }}.tar.gz
  sha256: a8a02d575905e50f6af90bbbc37d23d7e1b027630897f0eeefed6a3fb3c22e07

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - websocket_server
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Pithikos/python-websocket-server
  summary: A simple fully working websocket-server in Python with no external dependencies
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
